### ISSUE TITLE
Are you able to set up multiple rings?

### ISSUE THREAD

**Issue by hardtofin** [jsb/RingMenu#19] opened 2019-08-22 13:01 UTC
I am not able to test this as the game isn't live so I was wondering if it's not is it something you could implement please?

**Comment by jsb** [comment] 2019-08-22 13:08
It's not possible in the current version (2.0.0). However, this is an often requested feature (see [this issue](https://github.com/jsb/RingMenu/issues/1)), and I'm currently working on it.

**Comment by jsb** [comment] 2019-08-22 13:09
(closed: duplicate of #1)

**Closed by jsb** 2019-08-22 13:09 UTC
Labels: duplicate, enhancement
